### PR TITLE
code review

### PR DESCRIPTION
**Pull request by phryneas**
Just a first skim. Maybe we could get that to run in CodeSandbox and add it as an official example, if you're up for that? :)

Right now, my only question would be: this seems to bind everything to the lifecycle of the whole application - is it also possible to bind that to the lifecycle of just a component?

### CODE REVIEW

**Comment by wobsoriano** [comment]
> Just a first skim. Maybe we could get that to run in CodeSandbox and add it as an official example, if you're up for that? :)
> 
> Right now, my only question would be: this seems to bind everything to the lifecycle of the whole application - is it also possible to bind that to the lifecycle of just a component?

We could move the `store.ts` contents to a component, named `StoreProvider`

```vue
<template>
    <slot />
</template>

<script lang="ts">
// imports

const StoreSymbol: InjectionKey<StoreSymbolInterface> = Symbol()

export default defineComponent({
    setup() {
        const store = ref(reduxStore.getState())

        const unsubscribeStore = reduxStore.subscribe(() => {
            store.value = reduxStore.getState()
        })

        const { refetch, unsubscribe } = reduxStore.dispatch(productApi.endpoints.getProducts.initiate())

        const result = computed(() => productApi.endpoints.getProducts.select()(store.value))
    
        const isLoading = computed(() => result.value.status === QueryStatus.pending)
        const error = computed(() => result.value.status === QueryStatus.rejected)
        const data = computed(() => result.value.data)

        onUnmounted(() => {
            unsubscribeStore()
            unsubscribe()
        })

        provide(StoreSymbol, {
            refetch,
            data,
            isLoading,
            error
        })
    }
})
</script>
```

and in the root component

```vue
<template>
  <StoreProvider>
    <Products />
  </StoreProvider>
</template>
```

**Comment by wobsoriano** [comment]
This looks good to me. Thanks!

**Comment by phryneas** [comment]
So, if you were to use 3 or 5 queries, could that be abstracted in some way or would each of those require their own provider?

I really have no idea of vue, so this might be a stupid question :)

**Comment by wobsoriano** [comment]
> So, if you were to use 3 or 5 queries, could that be abstracted in some way or would each of those require their own provider?
> 
> I really have no idea of vue, so this might be a stupid question :)

I think we can put the crud actions in a single file and just import it... just to make the code shorter in components lol if I understand correctly

**Comment by phryneas** [comment]
Yeah, it's also a bit of a difference between React and Vue apparently, so I was just applying the wrong concept in my head :)

In React, you just wrap your whole application in a single provider for the redux store.
And then you can do `useSelector(state => state.y.z)` in any number of components and that component will automatically be subscribed to just that one selector.

But from what I understand, you really need one provider (in React, that would be a old style thing called a Higher-Order-Component) per subscription in Vue - so this seems to be 100% right :)

**Pull request merged**
